dist: trusty
sudo: required
osx_image: xcode8
language: java

os:
  - linux
  # - osx DISABLE FOR NOW UNTIL LINUX WORKING

env:
  - BAZEL=0.24.0 LANG=java RULE=proto_library

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      OS=darwin
    else
      sysctl kernel.unprivileged_userns_clone=1
      OS=linux
    fi
    wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL}/bazel-${BAZEL}-installer-${OS}-x86_64.sh"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

script:
  - |
    cd "${LANG}/example/${LANG}_${RULE}" && bazel build //:*

notifications:
  email: false
